### PR TITLE
Added "Dark Knight: A True Batman" under Autobiographical

### PR DESCRIPTION
**Pull request by nischalbasuti**
Added "Dark Night: A True Batman Story" by Paul Dini, Eduardo Risso under "Autobiographical"

### CODE REVIEW

**Comment by SaptakS** [comment]
Why under autobiographical and not superhero?

**Comment by nischalbasuti** [comment]
From goodreads:
This is a Batman story like no other—the harrowing and eloquent autobiographical tale of writer Paul Dini’s courageous struggle to overcome a desperate situation.

**Comment by SaptakS** [comment]
ok.resolve the merge conflict please.

**Comment by nischalbasuti** [comment]
done.

**Comment by SaptakS** [comment]
Can you please clean the Pull Request. It seems to have included all the commits by others in it. Please include only your commits and squash them. Thanks.

**Pull request closed without merging**
