### PR TITLE
Add Battle Angel Alita in the Fiction category and Hellboy in superhero category

### PR DESCRIPTION
**Pull request by LaurentLeVan-zz**

### CODE REVIEW

**Comment by SaptakS** [comment]
Please resolve merge conflict

**Comment by LaurentLeVan-zz** [comment]
Sorry, had some issues but now it's correct.

**Comment by SaptakS** [comment]
Please squash the commits. Thanks. :)

**Comment by LaurentLeVan-zz** [comment]
Maybe it will be better if I delete my fork and do it again no ?

**Comment by SaptakS** [comment]
@LaurentLeVan that's the easy way of doing it. It surely will work that way. :)

**Pull request closed without merging**
